services:
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    command: >
      redis-server --port 6379 --appendonly yes
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    restart: always
    volumes:
      - ./vectorstore:/home/python/app/vectorstore
      - ./rag_files:/home/python/app/rag_files
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - evolution-api
      - db
      - redis

volumes:
  evolution_instances:
  postgres_data:
  redis_data:
  vectorstore:
  rag_files:
