from decouple import config

OPENAI_API_KEY = config("OPENAI_API_KEY")
OPENAI_MODEL_NAME = config("OPENAI_MODEL_NAME")
OPENAI_MODEL_TEMPERATURE = config("OPENAI_MODEL_TEMPERATURE")
EVOLUTION_API_URL = config("EVOLUTION_API_URL")
EVOLUTION_INSTANCE_NAME = config("EVOLUTION_INSTANCE_NAME")
EVOLUTION_AUTHENTICATION_API_KEY = config("AUTHENTICATION_API_KEY")
