# Generated by Django 5.2.6 on 2025-09-21 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('umidade', models.FloatField()),
                ('condutividade', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('ph', models.FloatField()),
                ('nitrogenio', models.FloatField()),
                ('fosforo', models.FloatField()),
                ('potassio', models.FloatField()),
                ('salinidade', models.FloatField()),
                ('tds', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
