# Generated by Django 5.2.6 on 2025-11-07 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.CharField(help_text='Nome do cultivo plantado (ex: Milho, Soja, Feijão)', max_length=100)),
                ('area', models.CharField(blank=True, help_text='Área ou talhão onde está plantado (opcional)', max_length=100, null=True)),
                ('data_plantio', models.DateField(blank=True, help_text='Data do plantio (opcional)', null=True)),
                ('umidade_min', models.FloatField(help_text='Umidade mínima ideal (%)')),
                ('umidade_ideal', models.FloatField(blank=True, help_text='Umidade ideal (%)', null=True)),
                ('umidade_max', models.FloatField(help_text='Umidade máxima ideal (%)')),
                ('temperatura_min', models.FloatField(help_text='Temperatura mínima ideal (°C)')),
                ('temperatura_ideal', models.FloatField(blank=True, help_text='Temperatura ideal (°C)', null=True)),
                ('temperatura_max', models.FloatField(help_text='Temperatura máxima ideal (°C)')),
                ('ph_min', models.FloatField(help_text='pH mínimo ideal')),
                ('ph_ideal', models.FloatField(blank=True, help_text='pH ideal', null=True)),
                ('ph_max', models.FloatField(help_text='pH máximo ideal')),
                ('nitrogenio_min', models.FloatField(help_text='Nitrogênio mínimo ideal (mg/kg)')),
                ('nitrogenio_ideal', models.FloatField(blank=True, help_text='Nitrogênio ideal (mg/kg)', null=True)),
                ('nitrogenio_max', models.FloatField(help_text='Nitrogênio máximo ideal (mg/kg)')),
                ('fosforo_min', models.FloatField(help_text='Fósforo mínimo ideal (mg/kg)')),
                ('fosforo_ideal', models.FloatField(blank=True, help_text='Fósforo ideal (mg/kg)', null=True)),
                ('fosforo_max', models.FloatField(help_text='Fósforo máximo ideal (mg/kg)')),
                ('potassio_min', models.FloatField(help_text='Potássio mínimo ideal (mg/kg)')),
                ('potassio_ideal', models.FloatField(blank=True, help_text='Potássio ideal (mg/kg)', null=True)),
                ('potassio_max', models.FloatField(help_text='Potássio máximo ideal (mg/kg)')),
                ('condutividade_min', models.FloatField(blank=True, help_text='Condutividade mínima ideal (uS/cm)', null=True)),
                ('condutividade_ideal', models.FloatField(blank=True, help_text='Condutividade ideal (uS/cm)', null=True)),
                ('condutividade_max', models.FloatField(blank=True, help_text='Condutividade máxima ideal (uS/cm)', null=True)),
                ('salinidade_min', models.FloatField(blank=True, help_text='Salinidade mínima ideal (mg/L)', null=True)),
                ('salinidade_ideal', models.FloatField(blank=True, help_text='Salinidade ideal (mg/L)', null=True)),
                ('salinidade_max', models.FloatField(blank=True, help_text='Salinidade máxima ideal (mg/L)', null=True)),
                ('tds_min', models.FloatField(blank=True, help_text='TDS mínimo ideal (mg/L)', null=True)),
                ('tds_ideal', models.FloatField(blank=True, help_text='TDS ideal (mg/L)', null=True)),
                ('tds_max', models.FloatField(blank=True, help_text='TDS máximo ideal (mg/L)', null=True)),
                ('alertas_ativos', models.BooleanField(default=True, help_text='Se os alertas devem ser enviados via WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta do Cultivo',
                'verbose_name_plural': 'Alertas do Cultivo',
                'ordering': ['-created_at'],
            },
        ),
    ]
