# Generated by Django 5.2.6 on 2025-09-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de telefone/celular do usuário', max_length=20, null=True),
        ),
    ]
