# Generated by Django 5.2.6 on 2025-09-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de telefone/celular do usuário (único se preenchido)', max_length=20, null=True, unique=True),
        ),
    ]
