name: Deploy TCC - Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build-and-push:
    name: "Build and push (Backend)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=${SHA}" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_REPOSITORY}}:${{ steps.generate_sha.outputs.sha }} -f backend/Dockerfile backend

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_REPOSITORY}}:${{ steps.generate_sha.outputs.sha }}
          docker tag ${{ secrets.DOCKERHUB_REPOSITORY}}:${{ steps.generate_sha.outputs.sha }} ${{ secrets.DOCKERHUB_REPOSITORY}}:latest
          docker push ${{ secrets.DOCKERHUB_REPOSITORY}}:latest

  deploy:
    name: "Deploy to VM"
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Pull image from docker hub
        run: sudo docker pull ${{ secrets.DOCKERHUB_REPOSITORY}}:latest

      - name: Remove docker container
        run: sudo docker rm -f tcc-backend

      - name: Run docker container
        run: |
          sudo docker run -d -p 8000:8000 \
            --restart always \
            -e DEBUG=${{ secrets.DEBUG }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }} \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e OPENAI_MODEL_NAME=${{ secrets.OPENAI_MODEL_NAME }} \
            -e OPENAI_MODEL_TEMPERATURE=${{ secrets.OPENAI_MODEL_TEMPERATURE }} \
            -e POSTGRES_ENGINE=${{ secrets.POSTGRES_ENGINE }} \
            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
            -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
            -e EVOLUTION_API_URL=${{ secrets.EVOLUTION_API_URL }} \
            -e EVOLUTION_INSTANCE_NAME=${{ secrets.EVOLUTION_INSTANCE_NAME }} \
            -e AUTHENTICATION_API_KEY=${{ secrets.AUTHENTICATION_API_KEY }} \
            -e CONFIG_SESSION_PHONE_VERSION=${{ secrets.CONFIG_SESSION_PHONE_VERSION }} \
            -e DATABASE_ENABLED=${{ secrets.DATABASE_ENABLED }} \
            -e DATABASE_PROVIDER=${{ secrets.DATABASE_PROVIDER }} \
            -e DATABASE_CONNECTION_URI=${{ secrets.DATABASE_CONNECTION_URI }} \
            -e DATABASE_CONNECTION_CLIENT_NAME=${{ secrets.DATABASE_CONNECTION_CLIENT_NAME }} \
            -e DATABASE_SAVE_DATA_INSTANCE=${{ secrets.DATABASE_SAVE_DATA_INSTANCE }} \
            -e DATABASE_SAVE_DATA_NEW_MESSAGE=${{ secrets.DATABASE_SAVE_DATA_NEW_MESSAGE }} \
            -e DATABASE_SAVE_MESSAGE_UPDATE=${{ secrets.DATABASE_SAVE_MESSAGE_UPDATE }} \
            -e DATABASE_SAVE_DATA_CONTACTS=${{ secrets.DATABASE_SAVE_DATA_CONTACTS }} \
            -e DATABASE_SAVE_DATA_CHATS=${{ secrets.DATABASE_SAVE_DATA_CHATS }} \
            -e DATABASE_SAVE_DATA_LABELS=${{ secrets.DATABASE_SAVE_DATA_LABELS }} \
            -e DATABASE_SAVE_DATA_HISTORIC=${{ secrets.DATABASE_SAVE_DATA_HISTORIC }} \
            -e CACHE_REDIS_ENABLED=${{ secrets.CACHE_REDIS_ENABLED }} \
            -e CACHE_REDIS_URI=${{ secrets.CACHE_REDIS_URI }} \
            -e CACHE_REDIS_PREFIX_KEY=${{ secrets.CACHE_REDIS_PREFIX_KEY }} \
            -e CACHE_REDIS_SAVE_INSTANCES=${{ secrets.CACHE_REDIS_SAVE_INSTANCES }} \
            -e CACHE_LOCAL_ENABLED=${{ secrets.CACHE_LOCAL_ENABLED }} \
            -e VECTOR_STORE_PATH=${{ secrets.VECTOR_STORE_PATH }} \
            -e RAG_FILES_DIR=${{ secrets.RAG_FILES_DIR }} \
            -e BUFFER_KEY_SUFIX=${{ secrets.BUFFER_KEY_SUFIX }} \
            -e DEBOUNCE_SECONDS=${{ secrets.DEBOUNCE_SECONDS }} \
            -e BUFFER_TTL=${{ secrets.BUFFER_TTL }} \
            -e OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }} \
            --name tcc-backend ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
