name: Deploy TCC - Backend

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: "Deploy to VM"
    runs-on: self-hosted

    steps:
      - name: Pull image from docker hub
        run: sudo docker pull ${{ secrets.DOCKERHUB_REPOSITORY}}:latest

      - name: Remove docker container
        run: sudo docker rm -f tcc-backend

      - name: Run docker container
        run: |
          echo docker run -d -p 8000:8000 \
            --restart always \
            -e DEBUG=${{ secrets.DEBUG }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }} \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e OPENAI_MODEL_NAME=${{ secrets.OPENAI_MODEL_NAME }} \
            -e OPENAI_MODEL_TEMPERATURE=${{ secrets.OPENAI_MODEL_TEMPERATURE }} \
            -e POSTGRES_ENGINE=${{ secrets.POSTGRES_ENGINE }} \
            -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
            -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
            -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
            -e AI_SYSTEM_PROMPT=${{ secrets.AI_SYSTEM_PROMPT }} \
            -e EVOLUTION_API_URL=${{ secrets.EVOLUTION_API_URL }} \
            -e EVOLUTION_INSTANCE_NAME=${{ secrets.EVOLUTION_INSTANCE_NAME }} \
            -e AUTHENTICATION_API_KEY=${{ secrets.AUTHENTICATION_API_KEY }} \
            -e CACHE_REDIS_URI=${{ secrets.CACHE_REDIS_URI }} \
            -e VECTOR_STORE_PATH=${{ secrets.VECTOR_STORE_PATH }} \
            -e RAG_FILES_DIR=${{ secrets.RAG_FILES_DIR }} \
            -e BUFFER_KEY_SUFIX=${{ secrets.BUFFER_KEY_SUFIX }} \
            -e DEBOUNCE_SECONDS=${{ secrets.DEBOUNCE_SECONDS }} \
            -e BUFFER_TTL=${{ secrets.BUFFER_TTL }} \
            -e OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }} \
            --name tcc-backend ${{ secrets.DOCKERHUB_REPOSITORY }}:latest
