name: Deploy TCC - Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-and-push:
    name: "Build and push (Frontend)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=${SHA}" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_REPOSITORY_FRONTEND}}:${{ steps.generate_sha.outputs.sha }} -f frontend/Dockerfile frontend

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKERHUB_REPOSITORY_FRONTEND}}:${{ steps.generate_sha.outputs.sha }}
          docker tag ${{ secrets.DOCKERHUB_REPOSITORY_FRONTEND}}:${{ steps.generate_sha.outputs.sha }} ${{ secrets.DOCKERHUB_REPOSITORY_FRONTEND}}:latest
          docker push ${{ secrets.DOCKERHUB_REPOSITORY_FRONTEND}}:latest

  deploy:
    name: "Deploy to VM"
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull ${{ secrets.DOCKERHUB_REPOSITORY_FRONTEND}}:latest

      - name: Remove docker container
        run: sudo docker rm -f tcc-frontend

      - name: Run docker container
        run: |
          sudo docker run -d --network host \
            --restart always \
            -e VITE_OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e VITE_OPENAI_MODEL_NAME=${{ secrets.OPENAI_MODEL_NAME }} \
            -e VITE_OPENAI_MODEL_TEMPERATURE=${{ secrets.OPENAI_MODEL_TEMPERATURE }} \
            --name tcc-frontend ${{ secrets.DOCKERHUB_REPOSITORY_FRONTEND}}:latest
